### ISSUE TITLE
Can't install on VoidLinux

### ISSUE THREAD

**Issue by sivakov512** [nabijaczleweli/cargo-update#86]
Hi!

On installation I got this:
```shell
make[2]: Leaving directory '/tmp/cargo-installjQ1lYZ/release/build/curl-sys-6820a45c1e770016/out/build/lib'
make[1]: Leaving directory '/tmp/cargo-installjQ1lYZ/release/build/curl-sys-6820a45c1e770016/out/build/lib'

--- stderr
fatal: not a git repository (or any of the parent directories): .git
configure: WARNING: OpenSSL headers and library versions do not match.
/home/sivakov512/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/lib/vtls/openssl.c:124:22: error: static declaration of 'OpenSSL_version_num' follows non-static declaration
 static unsigned long OpenSSL_version_num(void)
                      ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bio.h:69:0,
                 from /usr/include/openssl/evp.h:67,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:149,
                 from /home/sivakov512/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/lib/urldata.h:86,
                 from /home/sivakov512/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/lib/vtls/openssl.c:41:
/usr/include/openssl/crypto.h:340:15: note: previous declaration of 'OpenSSL_version_num' was here
 unsigned long OpenSSL_version_num(void);
               ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:2023: vtls/libcurl_la-openssl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:734: all] Error 2
make: *** [Makefile:897: all-recursive] Error 1
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/sivakov512/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/build.rs:224:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: build_script_build::fail
   7: build_script_build::run
   8: build_script_build::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  13: main
  14: __libc_start_main
             at ../csu/libc-start.c:308
  15: _start
             at ../sysdeps/x86_64/start.S:120

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.5.2`, intermediate artifacts can be found at `/tmp/cargo-installjQ1lYZ`

Caused by:
  build failed
```

**Comment by mati865** [comment]
Error comes from `curl-sys` crate, you should report it there.

**Comment by nabijaczleweli** [comment]
That is quite right, cheers. And please do drop a link here for tracking purposes, would you?

**Comment by WnP** [comment]
Installing `libcurl-devel` fix this issue

**Comment by mati865** [comment]
@WnP this issue was fixed by curl-sys 0.4.6 released 19 days ago.

**Comment by WnP** [comment]
@mati865 good news, I guess this issue could be closed then.

**Comment by WnP** [comment]
`curl-sys` still doesn't compile on void linx without `libcurl-devel` even with `curl-sys==0.4.8` (latest).

Here is a simpler test case:

directory structure:
```
.
├── Dockerfile
└── test_curl_sys
    ├── Cargo.toml
    └── src
        └── main.rs
```

- `Dockerfile`:
```dockerfile
FROM voidlinux/voidlinux

COPY test_curl_sys /test_curl_sys
RUN xbps-install -Sy \
    rust cargo libressl-devel \
    cmake make gcc pkg-config \
    && cd test_curl_sys \
    && cargo run
```
- `Cargo.toml`:
```toml
[package]
name = "test_curl_sys"
version = "0.1.0"
authors = ["me <me@here.io>"]

[dependencies]
curl-sys = "0.4.8"
```
- `main.rs`:
```rust
fn main() {
    println!("Hello curl-sys");
}
```

I guess the issue is related to the fact that void linux use `libressl` which is an `openssl` fork, which could explain the version mismatch issue during compilation.

By the way installing `libcurl-devel` still fix this issue.

I just put this here as a reminder.
